language: go
services:
- docker
go:
- 1.8
addons:
  apt:
    packages:
    - upx-ucl
install:
- go get github.com/golang/dep/cmd/dep
- dep ensure
script:
- make release
- upx bin/assert-aws-iam-permissions
after_deploy:
- make docker VERSION=$TRAVIS_TAG
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=mattdeboer/assert-aws-iam-permissions
- docker push $REPO:$TRAVIS_TAG
- docker tag $REPO:$TRAVIS_TAG $REPO:latest
- docker push $REPO:latest
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: p2ER+ldT8/I8TGS+4AgNu3sf/qrcimLGwiGLkLS/b155rV4GzhPNzmsC0KmV41v0mmxncMg5UmUrhr7CZgGMq84+2HUnagepUWi+AJ4XAivea6yXUqDD4yahBImKXcBp5AjpGVjf8ylwi2y3LOxesozJNJSA+DpRt+96u91PEG+4XS0KZYwGlRjCDLz1QPJD0s9X4WMXOgWxOMR6mkz3foYnSP9y4Z68YVTC5YHdWa68b4dgoUNiITPqbYx9MS+hAswCuwAVbr02+kC3D0GJ3V9d6b3V72Ztt78Q6eEEmAC5qNtYfBuEg1OaNyf1/34E28YWRz8/eNw6NmpklMkMZXs3jhYPOO1cqOetXxGbwBIoQ5cxWaz2d2RWxEbf/UxOUw9Cny/QyTPtIY5EpBoJ3hYWQv4T9qQW7ofvy48fR+CDKTNY4JEq407HJZCxcCKCqhWTVqZowM5IrA4YjP8+yYcDiHWFKXhrsVAxMIZixy0BrII2fqrhzali3R7TR443INXYQC6fb6V/+87pltnf63LnCibPPAS6ET+QZPgVknNE7hPYx/o2DYll6bwfpL4dex6WySngavwWW6hHluqM6XYNtuborv6nUb5cA2HJr8HI4eMfy7iVEpwszPP8HbwGRcxf1Or0fPadXshVerrtlbeVlRjdm1HwbRdeGcRQmSc=
  file: bin/assert-aws-iam-permissions
  on:
    repo: matt-deboer/assert-aws-iam-permissions
    tags: true
env:
  global:
  - secure: yuyOSCAWcvQ89PbMjjtdsAEDXHzIDMRl8QX6kI5ZC9yD10venx/blarfVWd5ewmmVXUobTOthllJLE3TmBw9ckyjZLAJ+pDB2PTgMIab0yMPazaaheYn+326QK6iJVazp3MxLujNnr1N0jZaiVLQ7K4SnIJb7fGjo4habFkMfFJ6g2RTMEmL7NzXWWcaagxLhUPunQFaa2p7bGJNDMhI5yanJ5iOAZ0xHzcAJsdf9icMk5f5FE05L6xiKmDaHIrfsICpNAIYCjBjwMqPWDKv8imSMvCifytdJ3fvs8+bhGOGUBJTN8dX1OAoPVTHm5+n4xT1B0NfN+db2ezQ1hm+YI9/Tc1D0Htd4G0EgFpq6sUu2u3MKYhJBBIYBC2FH7Q4pJfOnB54d4k+EKruzmivk6P/tI8JJLDiaZP0kXcxy4r8vwMdSuzyjq+K5b0izVhYIOByWmyZx4RKtsf3eecJ50ymGZW8JV1uk92wBLk1Ps8oHc+oAdl+mFiagKCmxUi/f2lvTFYoEjZlOKp/uiGu+5VbOLSgaebqpnJiv45VMQt7AjYNNGXTisHFb5Ehc3PGq65neLRqqxGnBFSfceftqu07YDYUXlvVOMwaC5iMxe249y5As/exgyU8niZ6QgRTNKyr9d+YCP1h0QFCkRsqpQFoo76Y9G54An3huRrL2Po=
  - secure: OSiNXYps+vyJ7G5nC8IeQJWTpj1+JB6ZKFYjSSmBYBc2ZPm7Kbd0OiqqYYDDPeZasiOmlE8nwMtg96BDIyx1Clj6OmSSD08SofULqP57qPClDk00ip3c7lfdqHlJtzSTYAPcJKdxPE10gODfB5cimFSZD4qBRCd8wGuXjFFb7RIBq1UHs7K/K67/Gy705hxvei/h65ARwObIL4TdBZJabGRMQVuW7++Cd1YoJAhrPWm5PgNWyPmr2JI1W07opmMVeAOriAK98vIv7feojO5OOlvFRyVjnkZy7BiPaBWSj9Bk0ODY5CSFyAlPC69IpIrgIHYjt7/da85q6Cv5hgvx/dNEPeI/3Yz52M4pFu+SyJfhChMBA2GF4jSZm7B3uOTJoWIdyJN/DS2bZ9zFuWptFqNEupg0taWDy9fUmLMKH09bV62KMHoXlc8Dc/T+upWjjhHrB/4Ds4/j0lWCPtVZJLXKWkightGZoqoZj1hel1hONPv8DC95UaM39ftiOkiQ/QnO8vC96aof2FcWj8cNV3r1ABgEtdabhcvWYw5TflQPE7MrM04ipBUxYwDRYZdGEUzsvxJ5UE7mZrDFLGM8DoRQH5yXRwALEctto3JmlyR+Dxx33PwoM4GaUee0MKVEZGQZ5QDCLBXeA/+ywDI1seqjRS8Y5RdyQUx/V3RAbGQ=
